spring:
  application:
    name: poo
  datasource:
    url: 'jdbc:sqlite:app.db'
    driver-class-name: org.sqlite.JDBC
  jpa:
    database-platform: org.hibernate.community.dialect.SQLiteDialect
  flyway:
    enabled: false
